name: miracle_shot
description: AI-powered photo enhancement app with adjustable coolness levels

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.2
  
  # Camera and Image
  camera: ^0.10.5+9
  image_picker: ^1.0.7
  image: ^4.1.7
  
  # Permissions
  permission_handler: ^11.3.0
  
  # Photo Management
  photo_manager: ^3.0.0
  image_gallery_saver: ^2.0.3
  
  # HTTP
  http: ^1.2.0
  dio: ^5.4.0
  
  # Storage
  shared_preferences: ^2.2.2
  path_provider: ^2.1.2
  
  # EXIF
  exif: ^3.3.0
  
  # Toast
  fluttertoast: ^8.2.4
  
  # State Management
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21